development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:7509ab36e55a3b722521ed241b76a36d@albacore.redistogo.com:9527/
  host: koi.redistogo.com
  port: 9527
  channel_prefix: Dialoq_production
